CREATE OR REPLACE TABLE %%LIB%%.MANZANPAL (
            ORDINAL_POSITION BIGINT GENERATED ALWAYS AS IDENTITY (
            START WITH 1,
            INCREMENT BY 1,
            NO ORDER,
            NO CYCLE,
            NO MINVALUE,
            NO MAXVALUE,
            CACHE 20
        ) NOT NULL NOT HIDDEN,
            HANDLED_TIMESTAMP TIMESTAMP(6) GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE
            TIMESTAMP NOT NULL NOT HIDDEN,
            SESSION_ID  VARCHAR(10) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            SYSTEM_REFERENCE_CODE VARCHAR(8) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            DEVICE_NAME VARCHAR(10) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            MODEL VARCHAR(4) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            SERIAL_NUMBER VARCHAR(15) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            RESOURCE_NAME VARCHAR(10) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            LOG_ID VARCHAR(8) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            PAL_TIMESTAMP TIMESTAMP NOT NULL NOT HIDDEN,
            REFERENCE_CODE VARCHAR(4) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            SECONDARY_CODE VARCHAR(8) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            TABLE_ID VARCHAR(8) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            SEQUENCE_NUM INTEGER NOT NULL NOT HIDDEN
        )
    NOT VOLATILE UNIT ANY KEEP IN MEMORY NO
    ON REPLACE DELETE ROWS;