CREATE OR REPLACE TABLE %%LIB%%.MANZANVLOG (
            ORDINAL_POSITION BIGINT GENERATED ALWAYS AS IDENTITY (
            START WITH 1,
            INCREMENT BY 1,
            NO ORDER,
            NO CYCLE,
            NO MINVALUE,
            NO MAXVALUE,
            CACHE 20
        ) NOT NULL NOT HIDDEN,
            HANDLED_TIMESTAMP TIMESTAMP(6) GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE
            TIMESTAMP NOT NULL NOT HIDDEN,
            SESSION_ID VARCHAR(10) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            MAJOR_CODE VARCHAR(4) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            MINOR_CODE VARCHAR(4) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            LOG_ID VARCHAR(8) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            LOG_TIMESTAMP TIMESTAMP NOT NULL NOT HIDDEN,
            TDE_NUM VARCHAR(8) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            TASK_NAME VARCHAR(16) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            SERVER_TYPE VARCHAR(30) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            EXCEPTION_ID VARCHAR(2) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            JOB VARCHAR(28) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            THREAD_ID VARCHAR(8) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            MODULE_OFFSET VARCHAR(8) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            MODULE_RU_NAME VARCHAR(8) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            MODULE_NAME VARCHAR(48) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            MODULE_ENTRY_POINT_NAME VARCHAR(128) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN
        )
    NOT VOLATILE UNIT ANY KEEP IN MEMORY NO
    ON REPLACE DELETE ROWS;