CREATE OR REPLACE TABLE %%LIB%%.MANZANOTH (
            ORDINAL_POSITION BIGINT GENERATED ALWAYS AS IDENTITY (
            START WITH 1,
            INCREMENT BY 1,
            NO ORDER,
            NO CYCLE,
            NO MINVALUE,
            NO MAXVALUE,
            CACHE 20
        ) NOT NULL NOT HIDDEN,
            HANDLED_TIMESTAMP TIMESTAMP(6) GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE
            TIMESTAMP NOT NULL NOT HIDDEN,
            SESSION_ID VARCHAR(10) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            EVENT VARCHAR(10) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN
        )
    NOT VOLATILE UNIT ANY KEEP IN MEMORY NO
    ON REPLACE DELETE ROWS;