CREATE OR REPLACE TABLE MANZANMSG (
            ORDINAL_POSITION BIGINT GENERATED ALWAYS AS IDENTITY (
            START WITH 1,
            INCREMENT BY 1,
            NO ORDER,
            NO CYCLE,
            NO MINVALUE,
            NO MAXVALUE,
            CACHE 20
        ) NOT NULL NOT HIDDEN,
            HANDLED_TIMESTAMP TIMESTAMP(6) GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE
            TIMESTAMP NOT NULL NOT HIDDEN,
            SESSION_ID VARCHAR(10) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            MESSAGE_ID VARCHAR(7) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            MESSAGE_TYPE VARCHAR(10) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            SEVERITY INTEGER NOT NULL NOT HIDDEN,
            JOB VARCHAR(28) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            SENDING_USRPRF VARCHAR(10) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            SENDING_PROGRAM_NAME VARCHAR(256) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            SENDING_MODULE_NAME VARCHAR(10) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            SENDING_PROCEDURE_NAME VARCHAR(1024) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN,
            MESSAGE_TIMESTAMP TIMESTAMP NOT NULL NOT HIDDEN,
            MESSAGE VARCHAR(4096) CCSID 1208 NOT NORMALIZED NOT NULL NOT HIDDEN
        )
    NOT VOLATILE UNIT ANY KEEP IN MEMORY NO
    ON REPLACE DELETE ROWS;