-- Compound (SESSION_ID, timestamp) indexes on the four event tables.
--
-- MANZANMSG, MANZANOTH, MANZANPAL, and MANZANVLOG already carry a SESSION_ID
-- column.  These indexes let per-instance polling queries filter by SESSION_ID
-- and sort by the relevant timestamp column without a full table scan.
--
-- CONTINUE HANDLERs swallow "index already exists" (SQLSTATE 42891) so the
-- script is idempotent and compatible with V7R5M0 and later.

BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42891' BEGIN END;
    CREATE INDEX MANZANMSG_SESSION_IDX
        ON MANZANMSG (SESSION_ID, HANDLED_TIMESTAMP DESC);
END;

BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42891' BEGIN END;
    CREATE INDEX MANZANOTH_SESSION_IDX
        ON MANZANOTH (SESSION_ID, HANDLED_TIMESTAMP DESC);
END;

BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42891' BEGIN END;
    CREATE INDEX MANZANPAL_SESSION_IDX
        ON MANZANPAL (SESSION_ID, PAL_TIMESTAMP DESC);
END;

BEGIN
    DECLARE CONTINUE HANDLER FOR SQLSTATE '42891' BEGIN END;
    CREATE INDEX MANZANVLOG_SESSION_IDX
        ON MANZANVLOG (SESSION_ID, LOG_TIMESTAMP DESC);
END;
