# This workflow will build the ILE component.
# It can be triggered by making changes in the ile directory and either pushing or creating a pull request into main.

name: IBM i build CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ile/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'ile/**'

env:
  remote_build_dir: /home/${{ secrets.IBMI_USER }}/build/${{ github.sha }}
  ci_build_lib: MZNCI

jobs:
  build:
    runs-on: ubuntu-latest

    environment: OSSBUILD

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Install NPM Dependencies
        run: npm i -g @ibm/ibmi-ci

      - name: Get short SHA ID
        run: |
          echo "short_sha=$(echo ${{ github.sha }} | head -c 5)" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Deploy to IBM i
        run: | 
          ici \
            --rcwd "${{ env.remote_build_dir }}" \
            --push "." \
            --cmd "/QOpenSys/pkgs/bin/gmake -C ile BUILDLIB=${{ env.ci_build_lib }}$short_sha uninstall all" \
            --ignore --cl "dltlib ${{ env.ci_build_lib }}$short_sha" \
            --rcwd ".." \
            --ignore --cmd "rm -fr ${{ env.remote_build_dir }}"
        env:
          IBMI_HOST: ${{ secrets.IBMI_HOST }}
          IBMI_USER: ${{ secrets.IBMI_USER }}
          IBMI_PASSWORD: ${{ secrets.IBMI_PASSWORD }}
          IBMI_SSH_PORT: ${{ secrets.IBMI_SSH_PORT }}