# This workflow will test Manzan

name: Test Manzan

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build Manzan-installer
        run: pwd; gmake manzan-installer-v0.0.0.jar

      - name: Run Manzan-installer
        working-directory: camel
        run: java -jar manzan-installer-v0.0.0.jar

      - name: Test Manzan
        working-directory: test
        run: ./runTests.sh