# This workflow will test Manzan

name: Test Manzan

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  remote_build_dir: /home/${{ secrets.IBMI_USER }}/testbuild/
  build_lib: MANZANTESTBLD
  dist_lib: MANZANTEST

jobs:
  build:
    runs-on: ubuntu-latest

    environment: OSSBUILD
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Install NPM Dependencies
        run: npm i -g @ibm/ibmi-ci

      - name: Install Manzan
        working-directory: test
        run: | 
          ici \
            --rcwd "${{ env.remote_build_dir }}" \
            --push "." \
            --cmd "/QOpenSys/pkgs/bin/gmake --jobs=1 install" \
            --ignore --cl "dltlib ${{ env.build_lib }}" \
            --ignore --cmd "rm -rf /QOpenSys/etc/manzan /opt/manzan"
        env:
          IBMI_HOST: ${{ secrets.IBMI_HOST }}
          IBMI_USER: ${{ secrets.IBMI_USER }}
          IBMI_PASSWORD: ${{ secrets.IBMI_PASSWORD }}
          IBMI_SSH_PORT: ${{ secrets.IBMI_SSH_PORT }}


      - name: Test Manzan
        working-directory: test
        run: | 
          ici \
            --rcwd "${{ env.remote_build_dir }}/test" \
            --cmd "/QOpenSys/pkgs/bin/gmake --jobs=1 all" \
        env:
          IBMI_HOST: ${{ secrets.IBMI_HOST }}
          IBMI_USER: ${{ secrets.IBMI_USER }}
          IBMI_PASSWORD: ${{ secrets.IBMI_PASSWORD }}
          IBMI_SSH_PORT: ${{ secrets.IBMI_SSH_PORT }}
